name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  firebase_core: ^1.7.0
  animated_text_kit: ^1.3.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^0.1.2
  firebase_auth: ^3.1.2
  modal_progress_hud: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
